### ISSUE TITLE
rule engine resource editor: fields of type file only visible when ssl enabled

### ISSUE THREAD

**Issue by kjellwinblad** [emqx/emqx-dashboard-web#376]
I'm trying to add a new field of type file to the resource editor for Kafka (the field is for the keytab file, which is needed for Kerberos authentication). I'm editing this file https://github.com/kjellwinblad/emqx-enterprise/blob/5b078c237be9681d1f7e9fbfba98ed5d02c1dceb/lib-ee/emqx_rule_actions/src/emqx_bridge_kafka_actions.erl (the kerberos_keytab field should be changed from a field of type string to a field of type file). The Kerberos support will go into emqx-enterprise 4.4 and then to 5.0.

Unfortunately, all fields of the type file are visible only if the "Enable SSL" field is set to true. This is unfortunate since it would be good if one could enable Kerberos authentication even when SSL is not enabled. I have identified this place https://github.com/emqx/emqx-dashboard-web/blob/master/src/views/RuleEngine/components/ResourceDialog.vue#L111-L116, which I think might be related to the behavior. I have noticed that one can use a field of type `cfgselect` to hide fields conditionally (see https://github.com/kjellwinblad/emqx-enterprise/blob/5b078c237be9681d1f7e9fbfba98ed5d02c1dceb/lib-ee/emqx_rule_actions/src/emqx_bridge_pulsar_actions.erl#L75-L89). So maybe we could remove the code that hides fields depending on if SSL is enabled and convert the resource schemas to use `cfgselect` instead? Do you know if there are any problems with this solution? A less intrusive but more hacky solution could be adding an additional condition to ensure that the kerberos_keytab field is displayed even when SSL Enabled is set to false.

**Comment by kjellwinblad** [comment]
As requested, I have attached a series of screenshots explaining what the issue is.

![kafka_resouce_issue_screenshot](https://user-images.githubusercontent.com/200374/176457048-1374fc24-44b0-4e39-9ca2-a593939d1265.jpg)

**Comment by Kinplemelon** [comment]
Hello, I'm Kinple who is solving this issue. I got the question you are facing from Shifan. Now the SSL (or some value like SSL) control all the fields which type is file, because the previous file fields seem to all be the config for SSL. For this issue, I will don't let the SSL field control the kerberos_keytab field, but if you want the kerberos_keytab just show when sasl_gssapi_kerberos is true, you should let sasl_gssapi_kerberos is a cfgselect. Like this
```json
{
...
"sasl_gssapi_kerberos": {
      "type": "cfgselect",
      "title": {
        "zh": "Enable SASL/GSSAPI _kerberos",
        "en": "Enable SASL/GSSAPI _kerberos"
      },
      "order": 3,
      "items": {
        "true": {
          // Kerberos Principal
          // Kerberos Keytab
        },
        "false": {
          // empty
        }
      },
      "enum": [true, false],
      "description": {
        "zh": "Enable SASL/GSSAPI _kerberos",
        "en": "Enable SASL/GSSAPI _kerberos"
      },
      "default": true
    }
...
}
```

I'm not sure I've made my expression clearly, so if there's something you don't quite understand, please let me know; if you'll be modifying the back-end code please also leave a comment and I'll provide you with a package you can use to test it.

**Comment by kjellwinblad** [comment]
@Kinplemelon:
> Now the SSL (or some value like SSL) control all the fields which type is file, [...].

Yes, this is exactly the problem this issue is about. Have you already fixed it?

> but if you want the kerberos_keytab just show when sasl_gssapi_kerberos is true, you should let sasl_gssapi_kerberos is a cfgselect. Like this:

Thank you, yes using cfgselect in the way you describe seems to be a good solution and is the one I have already implemented. See: https://github.com/kjellwinblad/emqx-enterprise/blob/ec71e9adddfcb5f8c93805b45d1d81baa4a4eadc/lib-ee/emqx_rule_actions/src/emqx_bridge_kafka_actions.erl#L153-L189

> if you'll be modifying the back-end code please also leave a comment and I'll provide you with a package you can use to test it.

Yes, I'm modifying the backend but I have already set up a development environment for the dashboard so I think it is enough if you push to `dev/4.4` and `dev/5.0.0` or some other branches if you want me to test before you push to one of the main branches. You can, of course, use commit ec71e9adddfcb5f8c93805b45d1d81baa4a4eadc from my repo https://github.com/kjellwinblad/emqx-enterprise to test your solution by yourself.

**Comment by Kinplemelon** [comment]
Oh, thank you for the development environment. Yes, I fixed the problem and it seems to work good in my environment.
If you want to check it, you can use https://github.com/emqx/emqx-dashboard-web/tree/dev/4.4

https://user-images.githubusercontent.com/26165221/176604837-0c59cbbb-e778-4e66-a5e3-c2149d28717a.mov

**Comment by Kinplemelon** [comment]
I think this issue has been resolved, if you haven't more questions, I will close it tomorrow.😀

**Comment by kjellwinblad** [comment]
@Kinplemelon thanks looks good. I will test it now. Can you also fix this in the `dev/5.0.0` or if possible merge the fix to that branch?

**Comment by kjellwinblad** [comment]
I have tested this now. The problem with the file field not appearing unless "Enable SSL" is true is now fixed. Unfortunately, one issue still remains. When the "Confirm" or "Test" button is clicked the "Kerberos Keytab" field seems to be cleared before anything is sent to the backend so nothing is actually received in the backed and the "file data" the user selected also disappear (this only happens when "Enable SSL" is set to false). This incorrect behavior stops if I comment out these lines: https://github.com/emqx/emqx-dashboard-web/blob/3ec764b04fabf84018aad50b42452861798bad83/src/views/RuleEngine/components/ResourceDialog.vue#L330-L335

@Kinplemelon  I would be very thankful if you you could fix this problem as well before the issue is closed as I think they are very related.

Btw, do you know if anyone has started to look at the other issue I reported, issue https://github.com/emqx/emqx-dashboard-web/issues/377. It also needs to be fixed for the Kafka Kerberos authentication support I'm working on.

**Comment by Kinplemelon** [comment]
> @Kinplemelon thanks looks good. I will test it now. Can you also fix this in the `dev/5.0.0` or if possible merge the fix to that branch?

the logic in 5.0 is not like thie 4.* version, there is no similar logic in 5.0, so I can't fix this in 5.0, because there should haven't  issue in 5.0

**Comment by Kinplemelon** [comment]
> Unfortunately, one issue still remains. When the "Confirm" or "Test" button is clicked the "Kerberos Keytab" field seems to be cleared before anything is sent to the backend so nothing is actually received in the backed and the "file data" the 
> Btw, do you know if anyone has started to look at the other issue I reported, issue https://github.com/emqx/emqx-dashboard-web/issues/377. It also needs to be fixed for the Kafka Kerberos authentication support I'm working on.
I will confirm these two problems and fix it.

**Comment by Kinplemelon** [comment]
I mock some data for test and it looks good, you can test by using dev/4.4 branch.

https://user-images.githubusercontent.com/26165221/177089865-69c833d0-8442-456d-945e-11fbc104cc57.mov

**Comment by Kinplemelon** [comment]
> I have tested this now. The problem with the file field not appearing unless "Enable SSL" is true is now fixed. Unfortunately, one issue still remains. When the "Confirm" or "Test" button is clicked the "Kerberos Keytab" field seems to be cleared before anything is sent to the backend so nothing is actually received in the backed and the "file data" the user selected also disappear (this only happens when "Enable SSL" is set to false). 

Fixed it,  please use the dev/4.4 branch to check.

**Comment by kjellwinblad** [comment]
I believe this is fixed now but with the new binary_file field I don't use the file field any more so I have not actually tested.

**Comment by Kinplemelon** [comment]
okay, I will close this issue
